steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=config.json.enc
  - --plaintext-file=config.json
  - --location=global
  - --keyring=thegym-global-keyring
  - --key=thegym-global-key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=app.yaml.enc
  - --plaintext-file=app.yaml
  - --location=global
  - --keyring=thegym-global-keyring
  - --key=thegym-global-key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=passwd.json.enc
  - --plaintext-file=passwd.json
  - --location=global
  - --keyring=thegym-global-keyring
  - --key=thegym-global-key
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
